### ISSUE TITLE
[BUG] Nightdesk-Lamp doesn't make light

### ISSUE THREAD

**Issue by zwibblTV** [Steven-Paw-Design/awesomeshop#7] opened 2020-12-17 22:15 UTC
### What is the Bug?:
The Nightdesk-Lamp doesn't make any light when rightklicking

### Server or Clientside?:
Server-/ clientside

### What did you do before that bug occured?:
rightklicked the lamp

### AwesomeShop-Version:
1.1.1

_Btw: Rather use "bedside lamp" as name, "Nightdesk-Lamp" is denglisch. And add a question for the Mod-version on github ^^_

**Comment by StevenPaw** [comment] 2020-12-17 23:13
Will be fixed in 1.2.0

**Comment by zwibblTV** [comment] 2020-12-18 10:01
Still not fixed in 1.2.0

**Comment by StevenPaw** [comment] 2020-12-18 11:12
I cant see any problem there in Forge 35.0.2 in Minecraft 1.16.4. When did this problem happen? What Mods do you use with it? I cant reproduce the bug

**Comment by zwibblTV** [comment] 2020-12-18 11:25
Forge - 35.1.12
When did this problem happen? - Nothing happens, when rightklicking on Lamp!
What Mods do you use with it? - 
- Absent by Design - https://www.curseforge.com/minecraft/mc-mods/absent-by-design
- Advanced Mining Dimension - https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension
- Angel Ring - https://www.curseforge.com/minecraft/mc-mods/angel-ring
- AppleSkin - https://www.curseforge.com/minecraft/mc-mods/appleskin
- Aquaculture 2 - https://www.curseforge.com/minecraft/mc-mods/aquaculture
- Architectury - https://www.curseforge.com/minecraft/mc-mods/architectury-forge
- AutoRegLib - https://www.curseforge.com/minecraft/mc-mods/autoreglib
- Back Tools - https://www.curseforge.com/minecraft/mc-mods/back-tools
- Better Muffling - https://www.curseforge.com/minecraft/mc-mods/better-muffling
- Better Title Screen - https://www.curseforge.com/minecraft/mc-mods/better-title-screen
- Biomes O' Plenty - https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty
- Bookshelf - https://www.curseforge.com/minecraft/mc-mods/bookshelf
- Builders Crafts & Additions- https://www.curseforge.com/minecraft/mc-mods/buildersaddition
- CC: Tweaked - https://www.curseforge.com/minecraft/mc-mods/cc-tweaked
- Chisels & Bits - https://www.curseforge.com/minecraft/mc-mods/chisels-bits
- Citadel - https://www.curseforge.com/minecraft/mc-mods/citadel
- Clumps - https://www.curseforge.com/minecraft/mc-mods/clumps
- Cloth Config API - https://www.curseforge.com/minecraft/mc-mods/cloth-config-forge
- Comforts - https://www.curseforge.com/minecraft/mc-mods/comforts
- Construction Wand - https://www.curseforge.com/minecraft/mc-mods/construction-wand
- Controlling - https://www.curseforge.com/minecraft/mc-mods/controlling
- Cooking for Blockheads - https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads
- Crash Utilities - https://www.curseforge.com/minecraft/mc-mods/crash-utilities
- Cucumber Library - https://www.curseforge.com/minecraft/mc-mods/cucumber
- Curios API - https://www.curseforge.com/minecraft/mc-mods/curios
- Dark Utilities - https://www.curseforge.com/minecraft/mc-mods/dark-utilities
- Decorative Blocks - https://www.curseforge.com/minecraft/mc-mods/decorative-blocks#c100
- Ding - https://www.curseforge.com/minecraft/mc-mods/ding
- Doggy Talents - https://www.curseforge.com/minecraft/mc-mods/doggy-talents
- Double Slabs - https://www.curseforge.com/minecraft/mc-mods/double-slabs
- Dungeon Crawl - https://www.curseforge.com/minecraft/mc-mods/dungeon-crawl#c311
- Engineer's Decor - https://www.curseforge.com/minecraft/mc-mods/engineers-decor
- Extended Lights - https://www.curseforge.com/minecraft/mc-mods/extended-lights-mod
- Falling Tree - https://www.curseforge.com/minecraft/mc-mods/falling-tree
- Fast Leaf Decay - https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay
- FTB Chunks - https://www.curseforge.com/minecraft/mc-mods/ftb-chunks
- FTB GUI Library - https://www.curseforge.com/minecraft/mc-mods/ftb-gui-library
- Gauges and Switches - https://www.curseforge.com/minecraft/mc-mods/redstone-gauges-and-switches
- GraveStone Mod - https://www.curseforge.com/minecraft/mc-mods/gravestone-mod
- iChunUtil - https://www.curseforge.com/minecraft/mc-mods/ichunutil
- Immersive Engineering - https://www.curseforge.com/minecraft/mc-mods/immersive-engineering
- Industrial Foregoing - https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing
- Inventory Tweaks Renewed - https://www.curseforge.com/minecraft/mc-mods/inventory-tweaks-renewed
- Iron Chests - https://www.curseforge.com/minecraft/mc-mods/iron-chests
- Just Enough Items (JEI) - https://www.curseforge.com/minecraft/mc-mods/jei
- Just Enough Resources (JER) - https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer
- KubeJS - https://www.curseforge.com/minecraft/mc-mods/kubejs
- Light Overlay - https://www.curseforge.com/minecraft/mc-mods/light-overlay
- Lollipop - https://www.curseforge.com/minecraft/mc-mods/lollipop
- Macaw's Bridges - https://www.curseforge.com/minecraft/mc-mods/macaws-bridges
- Macaw's Doors - https://www.curseforge.com/minecraft/mc-mods/macaws-doors/
- Macaw's Roofs - https://www.curseforge.com/minecraft/mc-mods/macaws-roofs
- Macaw's Trapdoors - https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors
- Macaw's Windows - https://www.curseforge.com/minecraft/mc-mods/macaws-windows
- Mekanism - https://www.curseforge.com/minecraft/mc-mods/mekanism
- Mekanism Additions - https://www.curseforge.com/minecraft/mc-mods/mekanism-additions
- Mekanism Generators - https://www.curseforge.com/minecraft/mc-mods/mekanism-generators
- Mekanism Tools - https://www.curseforge.com/minecraft/mc-mods/mekanism-tools
- Miner's Helmet - https://www.curseforge.com/minecraft/mc-mods/miners-helmet
- Mod Name Tooltip - https://www.curseforge.com/minecraft/mc-mods/mod-name-tooltip
- Morpheus - https://www.curseforge.com/minecraft/mc-mods/morpheus
- Mouse Tweaks - https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks
- MrCrayfishs Furniture Mod - https://mrcrayfish.com/mods?id=cfm
- Mystical Agradditions - https://www.curseforge.com/minecraft/mc-mods/mystical-agradditions
- Mystical Agriculture - https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture
- Nature's Compass - https://www.curseforge.com/minecraft/mc-mods/natures-compass
- Neat - https://www.curseforge.com/minecraft/mc-mods/neat
- OpenBlocks Elevator - https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator
- OptiFine - https://www.optifine.net/home
- Pam's HarvestCraft 2-Food Core - https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-core
- PneumaticCraft: Repressurized - https://www.curseforge.com/minecraft/mc-mods/pneumaticcraft-repressurized
- Polymorph - https://www.curseforge.com/minecraft/mc-mods/polymorph
- Quark - https://www.curseforge.com/minecraft/mc-mods/quark
- Rats - https://www.curseforge.com/minecraft/mc-mods/rats
- ReAuth - https://www.curseforge.com/minecraft/mc-mods/reauth
- Refined Storage - https://www.curseforge.com/minecraft/mc-mods/refined-storage
- Refined Storage Addons - https://www.curseforge.com/minecraft/mc-mods/refined-storage-addons
- Refined Storage: Requestify - https://www.curseforge.com/minecraft/mc-mods/rs-requestify
- Rhino - https://www.curseforge.com/minecraft/mc-mods/rhino
- Runelic - https://www.curseforge.com/minecraft/mc-mods/runelic
- Scuba Gear - https://www.curseforge.com/minecraft/mc-mods/scuba-gear
- Security Craft - https://www.curseforge.com/minecraft/mc-mods/security-craft
- Silent Gear - https://www.curseforge.com/minecraft/mc-mods/silent-gear
- Silent Lib - https://www.curseforge.com/minecraft/mc-mods/silent-lib
- Simple Farming - https://www.curseforge.com/minecraft/mc-mods/simple-farming
- Simple Magnets - https://www.curseforge.com/minecraft/mc-mods/simple-magnets
- Sit - https://www.curseforge.com/minecraft/mc-mods/sit
- Storage Drawers - https://www.curseforge.com/minecraft/mc-mods/storage-drawers
- The One Probe - https://www.curseforge.com/minecraft/mc-mods/the-one-probe
- Titanium - https://www.curseforge.com/minecraft/mc-mods/titanium
- Torch Slabs Mod - https://www.curseforge.com/minecraft/mc-mods/torchslabs-mod
- Torchmaster - https://www.curseforge.com/minecraft/mc-mods/torchmaster
- Trash Cans - https://www.curseforge.com/minecraft/mc-mods/trash-cans
- Ultimate Car Mod - https://www.curseforge.com/minecraft/mc-mods/ultimate-car-mod
- Useful Backpacks - https://www.curseforge.com/minecraft/mc-mods/useful-backpacks
- U Team Core - https://www.curseforge.com/minecraft/mc-mods/u-team-core
- Wall-Jump! - https://www.curseforge.com/minecraft/mc-mods/wall-jump
- Wetstone - https://www.curseforge.com/minecraft/mc-mods/wetstone
- Wyrmroost - https://www.curseforge.com/minecraft/mc-mods/wyrmroost

**Comment by StevenPaw** [comment] 2020-12-18 11:34
The problem seems to be Optifine.... Don't know about a fix for now. But if you need to use this feature you can just disable Optifine. I will look into it, but there will be no fix right now because its another mod known for compatibility issues. I hope to find some solution soon!

**Closed as completed by StevenPaw** 2020-12-18 11:34 UTC
Labels: bug, question
